import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import peopleRouter from "./people";
import academicRouter from "./academic";
import edupulseRouter from "./edupulse";
import partnersRouter, { publicPartnersRouter } from "./partners";
import bootstrapRouter from "./bootstrap";
import devOwnerAccessDiagnosticRouter from "./dev-owner-access-diagnostic";
import platformRouter from "./platform";
import attendanceRouter from "./attendance";
import attendanceFamilyRouter from "./attendance-family";
import attendanceDiscrepancyResolutionRouter from "./attendance-discrepancy-resolution";
import academicWorkRouter from "./academic-work";
import academicResultsRouter from "./academic-results";
import academicTimetableRouter from "./academic-timetable";
import curriculumLearningRouter from "./curriculum-learning";
import peopleImportsRouter from "./people-imports";
import financeRouter from "./finance";
import financeNotificationsRouter from "./finance-notifications";
import invoiceNotificationsRouter from "./invoice-notifications";
import platformCompanyEmployeesRouter from "./platform-company-employees";
import communicationInboxRouter from "./communication-inbox";
import communicationPolicyRouter from "./communication-policy";
import { createCommunicationCampaignsRouter } from "./communication-campaigns";
import libraryRouter from "./library";
import operationsRouter from "./operations";
import reportingRouter from "./reporting";
import deviceActivationRouter from "./device-activation";
import studentPhotosRouter from "./student-photos";
import internalEmployeeInvitationsRouter from "./internal-employee-invitations";
import schoolInvitationManagementRouter from "./school-invitation-management";
import companyAccountantRouter from "./company-accountant";
import employeeNfcRouter from "./employee-nfc";
import nfcPrintableRouter from "./nfc-printable";
import { staffNfcBillingRouter } from "./staff-nfc-billing";
import schoolWorkflowsRouter from "./school-workflows";
import transportRouter from "./transport";
import settlementPayrollRouter from "./settlement-payroll";
import admissionsExpansionRouter from "./admissions-expansion";
import studentCareRouter from "./student-care";
import schoolSecurityCoreRouter from "./school-security-core";
import schoolSecurityOperationsRouter from "./school-security-operations";
import { createParentCommunicationRouter } from "./parent-communication";
import { requireSecurityAccess } from "../services/school-security-core-service";
import promotionExpansionRouter from "./promotion-expansion";
import subscriptionEnforcementRouter from "./subscription-enforcement";

const router: IRouter = Router();

router.use(healthRouter);
router.use(bootstrapRouter);
if (process.env.NODE_ENV === "development") {
  router.use(devOwnerAccessDiagnosticRouter);
}
router.use(publicPartnersRouter);
// Anonymous admissions handlers authenticate applicants with receipt credentials;
// school handlers apply their own operational authorization before every access.
router.use(admissionsExpansionRouter);
// Device credentials authenticate independently of Clerk. Every human-facing
// attendance handler applies requireAuthentication() explicitly.
router.use(attendanceRouter);
router.use(employeeNfcRouter);
router.use(nfcPrintableRouter);
router.use(authRouter);
router.use(subscriptionEnforcementRouter);
router.use(studentCareRouter);
router.use(schoolSecurityCoreRouter);
router.use(schoolSecurityOperationsRouter);
router.use(createParentCommunicationRouter(requireSecurityAccess));
router.use(promotionExpansionRouter);
router.use(peopleRouter);
router.use(academicRouter);
router.use(edupulseRouter);
router.use(partnersRouter);
router.use(platformRouter);
router.use(platformCompanyEmployeesRouter);
router.use(attendanceFamilyRouter);
router.use(attendanceDiscrepancyResolutionRouter);
router.use(academicWorkRouter);
router.use(academicResultsRouter);
router.use(academicTimetableRouter);
router.use(curriculumLearningRouter);
router.use(peopleImportsRouter);
router.use(financeRouter);
router.use(financeNotificationsRouter);
router.use(invoiceNotificationsRouter);
router.use(communicationInboxRouter);
router.use(communicationPolicyRouter);
router.use(createCommunicationCampaignsRouter(requireSecurityAccess));
router.use(libraryRouter);
router.use(operationsRouter);
router.use(reportingRouter);
router.use(deviceActivationRouter);
router.use(studentPhotosRouter);
router.use(internalEmployeeInvitationsRouter);
router.use(schoolInvitationManagementRouter);
router.use(companyAccountantRouter);
router.use(staffNfcBillingRouter);
router.use(schoolWorkflowsRouter);
router.use(transportRouter);
router.use(settlementPayrollRouter);

export default router;
