import { sql } from "drizzle-orm";
import {
  bigserial,
  bigint,
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgTable,
  serial,
  text,
  timestamp,
  unique,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import {
  appUsers,
  attendanceEvents,
  deviceSchoolBindings,
  employees,
  nfcCards,
  schools,
  students,
} from "./edupulse";

export const securityLocations = pgTable("security_locations", {
  id: serial("id").primaryKey(),
  schoolId: integer("school_id").notNull().references(() => schools.id),
  name: text("name").notNull(),
  description: text("description"),
  zoneType: text("zone_type").notNull().default("OTHER"),
  status: text("status").notNull().default("ACTIVE"),
  createdByUserId: integer("created_by_user_id").references(() => appUsers.id),
  updatedByUserId: integer("updated_by_user_id").references(() => appUsers.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("security_locations_zone_type_check", sql`${table.zoneType} IN ('GATE','CAMPUS','BUILDING','OTHER')`),
  check("security_locations_status_check", sql`${table.status} IN ('ACTIVE','INACTIVE')`),
  unique("security_locations_name_unique").on(table.schoolId, table.name),
  unique("security_locations_id_school_unique").on(table.id, table.schoolId),
  index("security_locations_school_status_idx").on(table.schoolId, table.status, table.name),
]);

export const securityReaders = pgTable("security_readers", {
  id: serial("id").primaryKey(),
  schoolId: integer("school_id").notNull().references(() => schools.id),
  locationId: integer("location_id").notNull(),
  deviceId: integer("device_id").notNull(),
  name: text("name").notNull(),
  status: text("status").notNull().default("ACTIVE"),
  permissions: text("permissions").array().notNull().default(sql`ARRAY['ENTRY','EXIT']::text[]`),
  createdByUserId: integer("created_by_user_id").references(() => appUsers.id),
  updatedByUserId: integer("updated_by_user_id").references(() => appUsers.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("security_readers_status_check", sql`${table.status} IN ('ACTIVE','INACTIVE')`),
  check("security_readers_permissions_check", sql`cardinality(${table.permissions}) > 0 AND ${table.permissions} <@ ARRAY['ENTRY','EXIT']::text[]`),
  unique("security_readers_device_school_unique").on(table.schoolId, table.deviceId),
  unique("security_readers_id_school_unique").on(table.id, table.schoolId),
  foreignKey({
    columns: [table.locationId, table.schoolId],
    foreignColumns: [securityLocations.id, securityLocations.schoolId],
    name: "security_readers_location_school_fk",
  }),
  foreignKey({
    columns: [table.deviceId, table.schoolId],
    foreignColumns: [deviceSchoolBindings.deviceId, deviceSchoolBindings.schoolId],
    name: "security_readers_device_school_fk",
  }),
  index("security_readers_school_status_idx").on(table.schoolId, table.status, table.locationId),
]);

export const securityStaffGrants = pgTable("security_staff_grants", {
  id: serial("id").primaryKey(),
  schoolId: integer("school_id").notNull().references(() => schools.id),
  userId: integer("user_id").notNull().references(() => appUsers.id),
  permissions: text("permissions").array().notNull(),
  status: text("status").notNull().default("ACTIVE"),
  expiresAt: timestamp("expires_at", { withTimezone: true }),
  grantedByUserId: integer("granted_by_user_id").notNull().references(() => appUsers.id),
  revokedByUserId: integer("revoked_by_user_id").references(() => appUsers.id),
  revokedAt: timestamp("revoked_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("security_staff_grants_permissions_check", sql`cardinality(${table.permissions}) > 0 AND ${table.permissions} <@ ARRAY['READ','MANAGE_READERS','MANAGE_CARDS','REVIEW_PRESENCE','SECURITY_READ','SECURITY_MANAGE','VISITOR_MANAGE','PICKUP_APPROVE','INCIDENT_MANAGE','EMERGENCY_BROADCAST','COMMUNICATION_SEND']::text[]`),
  check("security_staff_grants_status_check", sql`${table.status} IN ('ACTIVE','REVOKED','EXPIRED')`),
  check("security_staff_grants_revocation_shape_check", sql`(${table.status}='ACTIVE' AND ${table.revokedAt} IS NULL AND ${table.revokedByUserId} IS NULL) OR (${table.status} IN ('REVOKED','EXPIRED') AND ${table.revokedAt} IS NOT NULL)`),
  unique("security_staff_grants_id_school_unique").on(table.id, table.schoolId),
  uniqueIndex("security_staff_grants_one_active_unique").on(table.schoolId, table.userId).where(sql`${table.status}='ACTIVE'`),
  index("security_staff_grants_user_idx").on(table.userId, table.schoolId, table.status),
]);

export const securitySchoolSettings = pgTable("security_school_settings", {
  schoolId: integer("school_id").primaryKey().references(() => schools.id),
  securityEnabled: boolean("security_enabled").notNull().default(true),
  parentEntryAlerts: boolean("parent_entry_alerts").notNull().default(true),
  parentExitAlerts: boolean("parent_exit_alerts").notNull().default(true),
  updatedByUserId: integer("updated_by_user_id").references(() => appUsers.id),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

export const securityEvents = pgTable("security_events", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  schoolId: integer("school_id").notNull().references(() => schools.id),
  readerId: integer("reader_id"),
  locationId: integer("location_id"),
  deviceId: integer("device_id").notNull(),
  attendanceEventId: integer("attendance_event_id"),
  nfcCardId: integer("nfc_card_id"),
  studentId: integer("student_id"),
  employeeId: integer("employee_id"),
  personType: text("person_type").notNull(),
  personNameSnapshot: text("person_name_snapshot"),
  admissionNumberSnapshot: text("admission_number_snapshot"),
  employeeNumberSnapshot: text("employee_number_snapshot"),
  classNameSnapshot: text("class_name_snapshot"),
  sectionSnapshot: text("section_snapshot"),
  locationNameSnapshot: text("location_name_snapshot"),
  readerNameSnapshot: text("reader_name_snapshot"),
  eventType: text("event_type").notNull(),
  identityResult: text("identity_result").notNull(),
  reasonCode: text("reason_code"),
  cardUidSha256: text("card_uid_sha256"),
  eventKey: text("event_key").notNull(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(),
  receivedAt: timestamp("received_at", { withTimezone: true }).notNull().defaultNow(),
  syncStatus: text("sync_status").notNull().default("SYNCED"),
  physicalControlStatus: text("physical_control_status").notNull().default("NOT_CONNECTED"),
  actorUserId: integer("actor_user_id").references(() => appUsers.id),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("security_events_person_type_check", sql`${table.personType} IN ('STUDENT','STAFF','UNKNOWN')`),
  check("security_events_type_check", sql`${table.eventType} IN ('ENTRY','EXIT')`),
  check("security_events_identity_result_check", sql`${table.identityResult} IN ('CONFIRMED','REJECTED')`),
  check("security_events_reason_code_check", sql`${table.reasonCode} IS NULL OR ${table.reasonCode} IN ('UNKNOWN_CARD','WRONG_SCHOOL','LOST_CARD','REVOKED_CARD','EXPIRED_CARD','INACTIVE_CARD','NOT_ASSIGNED','INACTIVE_PERSON','NO_CURRENT_PLACEMENT','STAFF_BILLING_INELIGIBLE','READER_INACTIVE','READER_PERMISSION_DENIED','SECURITY_DISABLED','IDENTITY_MISMATCH','OTHER')`),
  check("security_events_sync_status_check", sql`${table.syncStatus} IN ('SYNCED')`),
  check("security_events_physical_control_check", sql`${table.physicalControlStatus}='NOT_CONNECTED'`),
  check("security_events_card_hash_check", sql`${table.cardUidSha256} IS NULL OR ${table.cardUidSha256} ~ '^[0-9a-f]{64}$'`),
  check("security_events_event_key_check", sql`length(${table.eventKey}) BETWEEN 1 AND 256`),
  check("security_events_person_shape_check", sql`(${table.personType}='STUDENT' AND ${table.studentId} IS NOT NULL AND ${table.employeeId} IS NULL) OR (${table.personType}='STAFF' AND ${table.employeeId} IS NOT NULL AND ${table.studentId} IS NULL) OR (${table.personType}='UNKNOWN' AND ${table.studentId} IS NULL AND ${table.employeeId} IS NULL)`),
  check("security_events_outcome_reason_check", sql`(${table.identityResult}='CONFIRMED' AND ${table.reasonCode} IS NULL AND ${table.personType}<>'UNKNOWN') OR (${table.identityResult}='REJECTED' AND ${table.reasonCode} IS NOT NULL)`),
  unique("security_events_id_school_unique").on(table.id, table.schoolId),
  unique("security_events_device_key_unique").on(table.schoolId, table.deviceId, table.eventKey),
  foreignKey({ columns: [table.readerId, table.schoolId], foreignColumns: [securityReaders.id, securityReaders.schoolId], name: "security_events_reader_school_fk" }),
  foreignKey({ columns: [table.locationId, table.schoolId], foreignColumns: [securityLocations.id, securityLocations.schoolId], name: "security_events_location_school_fk" }),
  foreignKey({ columns: [table.deviceId, table.schoolId], foreignColumns: [deviceSchoolBindings.deviceId, deviceSchoolBindings.schoolId], name: "security_events_device_school_fk" }),
  foreignKey({ columns: [table.attendanceEventId, table.schoolId], foreignColumns: [attendanceEvents.id, attendanceEvents.schoolId], name: "security_events_attendance_school_fk" }),
  foreignKey({ columns: [table.nfcCardId, table.schoolId], foreignColumns: [nfcCards.id, nfcCards.schoolId], name: "security_events_card_school_fk" }),
  foreignKey({ columns: [table.studentId, table.schoolId], foreignColumns: [students.id, students.schoolId], name: "security_events_student_school_fk" }),
  foreignKey({ columns: [table.employeeId, table.schoolId], foreignColumns: [employees.id, employees.schoolId], name: "security_events_employee_school_fk" }),
  index("security_events_school_time_idx").on(table.schoolId, table.occurredAt, table.id),
  index("security_events_school_result_time_idx").on(table.schoolId, table.identityResult, table.occurredAt),
  index("security_events_student_time_idx").on(table.schoolId, table.studentId, table.occurredAt).where(sql`${table.studentId} IS NOT NULL`),
  index("security_events_employee_time_idx").on(table.schoolId, table.employeeId, table.occurredAt).where(sql`${table.employeeId} IS NOT NULL`),
  index("security_events_card_hash_idx").on(table.schoolId, table.cardUidSha256, table.occurredAt).where(sql`${table.cardUidSha256} IS NOT NULL`),
]);

export const campusPresence = pgTable("campus_presence", {
  id: bigserial("id", { mode: "number" }).primaryKey(),
  schoolId: integer("school_id").notNull().references(() => schools.id),
  personType: text("person_type").notNull(),
  studentId: integer("student_id"),
  employeeId: integer("employee_id"),
  state: text("state").notNull(),
  lastSecurityEventId: bigint("last_security_event_id", { mode: "number" }).notNull(),
  lastOccurredAt: timestamp("last_occurred_at", { withTimezone: true }).notNull(),
  reviewReason: text("review_reason"),
  resolvedByUserId: integer("resolved_by_user_id").references(() => appUsers.id),
  resolutionReason: text("resolution_reason"),
  reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
}, (table) => [
  check("campus_presence_person_type_check", sql`${table.personType} IN ('STUDENT','STAFF')`),
  check("campus_presence_state_check", sql`${table.state} IN ('ON_CAMPUS','OFF_CAMPUS','REQUIRES_REVIEW')`),
  check("campus_presence_person_shape_check", sql`(${table.personType}='STUDENT' AND ${table.studentId} IS NOT NULL AND ${table.employeeId} IS NULL) OR (${table.personType}='STAFF' AND ${table.employeeId} IS NOT NULL AND ${table.studentId} IS NULL)`),
  unique("campus_presence_id_school_unique").on(table.id, table.schoolId),
  foreignKey({ columns: [table.lastSecurityEventId, table.schoolId], foreignColumns: [securityEvents.id, securityEvents.schoolId], name: "campus_presence_event_school_fk" }),
  foreignKey({ columns: [table.studentId, table.schoolId], foreignColumns: [students.id, students.schoolId], name: "campus_presence_student_school_fk" }),
  foreignKey({ columns: [table.employeeId, table.schoolId], foreignColumns: [employees.id, employees.schoolId], name: "campus_presence_employee_school_fk" }),
  uniqueIndex("campus_presence_student_unique").on(table.schoolId, table.studentId).where(sql`${table.studentId} IS NOT NULL`),
  uniqueIndex("campus_presence_employee_unique").on(table.schoolId, table.employeeId).where(sql`${table.employeeId} IS NOT NULL`),
  index("campus_presence_dashboard_idx").on(table.schoolId, table.state, table.personType, table.lastOccurredAt),
]);